KENYA/KENYA/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('KISUMU.urls'))
]

KENYA/KISUMU/urls.py
from django.urls import path
from . import views

app_name='kisumu'

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact' ),
    path('about/',views.about, name='about' ),

]

KENYA/KISUMU/models.py
from django.db import models

# Create your models here.

KENYA/KISUMU/views.py
from django.shortcuts import render
def home(request):
    return render(request,'home.html',  {'bike': 'home'})

def about(request):
    return render(request, 'about.html',  {'bike': 'about'})

def contact(request):
    return render(request, 'contact.html', {'bike': 'contact'})



# Create your views here.

KENYA/KISUMU/templates/about.html
{% extends 'layout.html' %}

{% block body %}

    <p> KISUMU HOSTS LAKE VICTORIA</p>

{% endblock %}

KENYA/KISUMU/templates/contact.html
{% extends 'layout.html' %}

{% block body %}

    <p> CONTACT ME TO VIEW THE LAKE </p>

{% endblock %}

KENYA/KISUMU/templates/home.html
{% extends 'layout.html' %}

{% block body %}

    <p> WELCOME TO KISUMU </p>

{% endblock %}

KENYA/KISUMU/templates/layout.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

<link rel="stylesheet" href="{% static 'style.css' %}">

</head>
<body>

<a class="{% if bike == 'home' %}two {% endif %}" href="{% url 'kisumu:home' %}">HOME</a>
<a class="{% if bike == 'about' %}two {% endif %}" href="{% url 'kisumu:about' %}">ABOUT</a>
<a class="{% if bike == 'contact' %}two {% endif %}" href="{% url 'kisumu:contact' %}">CONTACT</a>




{% block body %}



{% endblock %}

</body>
</html>